# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cvTransfer_pb2 as cvTransfer__pb2


class PointSenderStub(object):
    """service to send all points through grc
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPoints = channel.unary_unary(
                '/transferPoints.PointSender/GetPoints',
                request_serializer=cvTransfer__pb2.dummyPoint.SerializeToString,
                response_deserializer=cvTransfer__pb2.AllPoints.FromString,
                )
        self.SetPoints = channel.unary_unary(
                '/transferPoints.PointSender/SetPoints',
                request_serializer=cvTransfer__pb2.AllPoints.SerializeToString,
                response_deserializer=cvTransfer__pb2.dummyPoint.FromString,
                )


class PointSenderServicer(object):
    """service to send all points through grc
    """

    def GetPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PointSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoints,
                    request_deserializer=cvTransfer__pb2.dummyPoint.FromString,
                    response_serializer=cvTransfer__pb2.AllPoints.SerializeToString,
            ),
            'SetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPoints,
                    request_deserializer=cvTransfer__pb2.AllPoints.FromString,
                    response_serializer=cvTransfer__pb2.dummyPoint.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transferPoints.PointSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PointSender(object):
    """service to send all points through grc
    """

    @staticmethod
    def GetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transferPoints.PointSender/GetPoints',
            cvTransfer__pb2.dummyPoint.SerializeToString,
            cvTransfer__pb2.AllPoints.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transferPoints.PointSender/SetPoints',
            cvTransfer__pb2.AllPoints.SerializeToString,
            cvTransfer__pb2.dummyPoint.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
