# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cvTransfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cvTransfer.proto',
  package='transferPoints',
  syntax='proto2',
  serialized_options=b'\252\002\016TransferPoints',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63vTransfer.proto\x12\x0etransferPoints\"k\n\tAllPoints\x12\x30\n\x03vec\x18\x01 \x03(\x0b\x32#.transferPoints.AllPoints.xyzVector\x1a,\n\txyzVector\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\"\x18\n\ndummyPoint\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x95\x01\n\x0bPointSender\x12\x42\n\tGetPoints\x12\x1a.transferPoints.dummyPoint\x1a\x19.transferPoints.AllPoints\x12\x42\n\tSetPoints\x12\x19.transferPoints.AllPoints\x1a\x1a.transferPoints.dummyPointB\x11\xaa\x02\x0eTransferPoints'
)




_ALLPOINTS_XYZVECTOR = _descriptor.Descriptor(
  name='xyzVector',
  full_name='transferPoints.AllPoints.xyzVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='transferPoints.AllPoints.xyzVector.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='transferPoints.AllPoints.xyzVector.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='transferPoints.AllPoints.xyzVector.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=143,
)

_ALLPOINTS = _descriptor.Descriptor(
  name='AllPoints',
  full_name='transferPoints.AllPoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vec', full_name='transferPoints.AllPoints.vec', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ALLPOINTS_XYZVECTOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=143,
)


_DUMMYPOINT = _descriptor.Descriptor(
  name='dummyPoint',
  full_name='transferPoints.dummyPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='transferPoints.dummyPoint.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=169,
)

_ALLPOINTS_XYZVECTOR.containing_type = _ALLPOINTS
_ALLPOINTS.fields_by_name['vec'].message_type = _ALLPOINTS_XYZVECTOR
DESCRIPTOR.message_types_by_name['AllPoints'] = _ALLPOINTS
DESCRIPTOR.message_types_by_name['dummyPoint'] = _DUMMYPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AllPoints = _reflection.GeneratedProtocolMessageType('AllPoints', (_message.Message,), {

  'xyzVector' : _reflection.GeneratedProtocolMessageType('xyzVector', (_message.Message,), {
    'DESCRIPTOR' : _ALLPOINTS_XYZVECTOR,
    '__module__' : 'cvTransfer_pb2'
    # @@protoc_insertion_point(class_scope:transferPoints.AllPoints.xyzVector)
    })
  ,
  'DESCRIPTOR' : _ALLPOINTS,
  '__module__' : 'cvTransfer_pb2'
  # @@protoc_insertion_point(class_scope:transferPoints.AllPoints)
  })
_sym_db.RegisterMessage(AllPoints)
_sym_db.RegisterMessage(AllPoints.xyzVector)

dummyPoint = _reflection.GeneratedProtocolMessageType('dummyPoint', (_message.Message,), {
  'DESCRIPTOR' : _DUMMYPOINT,
  '__module__' : 'cvTransfer_pb2'
  # @@protoc_insertion_point(class_scope:transferPoints.dummyPoint)
  })
_sym_db.RegisterMessage(dummyPoint)


DESCRIPTOR._options = None

_POINTSENDER = _descriptor.ServiceDescriptor(
  name='PointSender',
  full_name='transferPoints.PointSender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=172,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPoints',
    full_name='transferPoints.PointSender.GetPoints',
    index=0,
    containing_service=None,
    input_type=_DUMMYPOINT,
    output_type=_ALLPOINTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetPoints',
    full_name='transferPoints.PointSender.SetPoints',
    index=1,
    containing_service=None,
    input_type=_ALLPOINTS,
    output_type=_DUMMYPOINT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POINTSENDER)

DESCRIPTOR.services_by_name['PointSender'] = _POINTSENDER

# @@protoc_insertion_point(module_scope)
